### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by sangyye** [Nerderrhein/nerderrhein.github.io#2]
Ich würde gerne den Inhalt des Blog unter die [MIT License](http://opensource.org/licenses/MIT) stellen. Brauche dafür aber die Zustimmung von @klein2de für [chat alias mosh](http://nerderrhein.de/2014/07/17/chat-alias-mosh/) und von @drj für [DNS mit nsd und unbound auf OpenBSD](http://nerderrhein.de/2014/01/26/dns-mit-nsd-und-unbound-auf-openbsd/). Würde gerne eure Meinung hören.

**Comment by sangyye** [comment]
Rückmeldung von @klein2de [via twitter](https://twitter.com/klein2/status/634459714013790209)

**Comment by drj** [comment]
Hi,
von mir aus kein Problem!

Danke,
Christoph (drj)
